services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/etherscan
      - INFURA_URL=${INFURA_URL}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
